[package]
name = "red-button-trigger-timestamp-comms"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", default-features = false }
serde_derive = "1.0"
defmt = { version = "0.3", optional = true }

[features]
std = []
print-defmt = ["defmt"]
